'use client'

import { useState, useCallback } from 'react'
import {
  RefreshCw,
  AlertCircle,
  CheckCircle2,
  Clock,
  TrendingUp,
  Eye,
  Copy,
  Check,
  ThumbsUp,
  ThumbsDown,
  Search,
} from 'lucide-react'
import {
  DossierResponse,
  EntityType,
  LensKey,
  LENS_LABELS,
} from './types'
import DossierSidebar from './DossierSidebar'
import { CollapsibleSection, extractRelatedEntities } from './DossierHelpers'

interface DossierResultsProps {
  dossier: DossierResponse
  lensKey: LensKey
  onNewSearch: () => void
  onRefresh: () => void
  onRelatedSearch: (query: string, entityType: EntityType) => void
}

export default function DossierResults({
  dossier,
  lensKey,
  onNewSearch,
  onRefresh,
  onRelatedSearch,
}: DossierResultsProps) {
  const [copied, setCopied] = useState(false)
  const [feedback, setFeedback] = useState<'up' | 'down' | null>(null)
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({})
  const labels = LENS_LABELS[lensKey]

  const toggleSection = (key: string) =>
    setCollapsed((prev) => ({ ...prev, [key]: !prev[key] }))

  const copyToClipboard = useCallback(() => {
    const s = dossier.synthesis
    const lines: string[] = [
      `# ${s.headline}`,
      '',
      s.dek,
      '',
      `## Bottom Line`,
      s.bottomLine,
    ]
    if (s.whyNow) {
      lines.push('', '## Why Now', s.whyNow)
    }
    if (s.whyItMatters.length > 0) {
      lines.push('', '## Why It Matters')
      s.whyItMatters.forEach((item) => lines.push(`- ${item}`))
    }
    if (s.proofPoints.length > 0) {
      lines.push('', '## Proof Points')
      s.proofPoints.forEach((pp, i) => lines.push(`${i + 1}. **${pp.label}** — ${pp.detail}`))
    }
    if (s.whatToWatch.length > 0) {
      lines.push('', '## What to Watch')
      s.whatToWatch.forEach((item) => lines.push(`→ ${item}`))
    }
    if (s.suggestedQuestions.length > 0) {
      lines.push('', '## Questions to Ask')
      s.suggestedQuestions.forEach((q) => lines.push(`- "${q}"`))
    }
    lines.push(
      '',
      '---',
      `*Generated by Relevant · ${dossier.entity.lensKey} lens · ${dossier.entity.lookbackDays}-day lookback · ${new Date(dossier.generatedAt).toLocaleDateString()}*`
    )
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [dossier])

  /* Extract related entities from timeline and proof points for suggestions */
  const relatedEntities = extractRelatedEntities(dossier)

  return (
    <>
      {/* Toolbar */}
      <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <button
          onClick={onNewSearch}
          className="rounded-lg bg-[var(--surface)] px-3 py-1.5 text-sm text-[var(--text-muted)] hover:bg-[var(--surface-strong)] hover:text-[var(--text)]"
        >
          ← New Search
        </button>
        <div className="flex flex-wrap items-center gap-2.5 text-xs text-[var(--text-soft)]">
          {dossier.status.cache.hit && dossier.status.cache.ageMinutes != null && (
            <span>Cached {Math.round(dossier.status.cache.ageMinutes)}m ago</span>
          )}
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setFeedback(feedback === 'up' ? null : 'up')}
              className={`flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-sm transition-colors ${
                feedback === 'up'
                  ? 'bg-accent-teal/10 text-accent-teal'
                  : 'bg-[var(--surface)] text-[var(--text-muted)] hover:bg-[var(--surface-strong)] hover:text-[var(--text)]'
              }`}
              title="Helpful"
            >
              <ThumbsUp className="h-3.5 w-3.5" />
            </button>
            <button
              onClick={() => setFeedback(feedback === 'down' ? null : 'down')}
              className={`flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-sm transition-colors ${
                feedback === 'down'
                  ? 'bg-accent-coral/10 text-accent-coral'
                  : 'bg-[var(--surface)] text-[var(--text-muted)] hover:bg-[var(--surface-strong)] hover:text-[var(--text)]'
              }`}
              title="Not helpful"
            >
              <ThumbsDown className="h-3.5 w-3.5" />
            </button>
          </div>
          <button
            onClick={copyToClipboard}
            className="flex items-center gap-1 rounded-lg bg-[var(--surface)] px-3 py-1.5 text-sm text-[var(--text-muted)] hover:bg-[var(--surface-strong)] hover:text-[var(--text)]"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-accent-teal" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                Copy
              </>
            )}
          </button>
          <button
            onClick={onRefresh}
            className="flex items-center gap-1 rounded-lg bg-[var(--surface)] px-3 py-1.5 text-sm text-[var(--text-muted)] hover:bg-[var(--surface-strong)] hover:text-[var(--text)]"
          >
            <RefreshCw className="h-3.5 w-3.5" />
            Refresh
          </button>
        </div>
      </div>

      {/* No coverage state */}
      {dossier.status.coverageBand === 'none' ? (
        <div className="flex min-h-[40vh] flex-col items-center justify-center gap-5 text-center">
          <AlertCircle className="h-10 w-10 text-[var(--text-soft)]" />
          <h2 className="text-lg font-semibold text-[var(--text)]">Not enough coverage yet</h2>
          <p className="max-w-md text-sm text-[var(--text-muted)]">
            Relevant hasn&apos;t collected enough signals about &ldquo;{dossier.entity.query}&rdquo;
            in the last {dossier.entity.lookbackDays} days to build a useful briefing.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-3">
            {dossier.entity.lookbackDays < 90 && (
              <button
                onClick={onRefresh}
                className="rounded-lg bg-[var(--surface)] px-4 py-2 text-sm text-[var(--text)] hover:bg-[var(--surface-strong)]"
              >
                Try 90-day lookback
              </button>
            )}
            <button
              onClick={onNewSearch}
              className="rounded-lg bg-[var(--accent)] px-4 py-2 text-sm font-medium text-white hover:opacity-90"
            >
              Try a different query
            </button>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-5">
          {/* LEFT COLUMN */}
          <div className="space-y-6 lg:col-span-3">
            {/* Metadata badges */}
            <div>
              <div className="mb-1 flex flex-wrap items-center gap-2 text-xs text-[var(--text-soft)]">
                <span className="rounded bg-[var(--surface)] px-2 py-0.5 capitalize">
                  {dossier.entity.entityType}
                </span>
                <span className="rounded bg-[var(--surface)] px-2 py-0.5 capitalize">
                  {dossier.entity.lensKey} lens
                </span>
                <span>{dossier.entity.lookbackDays}-day lookback</span>
              </div>
              <h2 className="font-display text-2xl font-bold leading-tight text-[var(--text)] sm:text-3xl">
                {dossier.synthesis.headline}
              </h2>
              {dossier.synthesis.dek && (
                <p className="mt-2 text-base leading-relaxed text-[var(--text-muted)]">
                  {dossier.synthesis.dek}
                </p>
              )}
            </div>

            {/* Label pills */}
            {(dossier.synthesis.opportunityLabel ||
              dossier.synthesis.riskLabel ||
              dossier.synthesis.tensionLabel) && (
              <div className="flex flex-wrap gap-2">
                {dossier.synthesis.opportunityLabel && (
                  <span className="rounded-full border border-accent-teal/20 bg-accent-teal/10 px-3 py-1 text-xs font-medium text-accent-teal">
                    ↑ {dossier.synthesis.opportunityLabel}
                  </span>
                )}
                {dossier.synthesis.riskLabel && (
                  <span className="rounded-full border border-accent-coral/20 bg-accent-coral/10 px-3 py-1 text-xs font-medium text-accent-coral">
                    ⚠ {dossier.synthesis.riskLabel}
                  </span>
                )}
                {dossier.synthesis.tensionLabel && (
                  <span className="rounded-full border border-accent-amber/20 bg-accent-amber/10 px-3 py-1 text-xs font-medium text-accent-amber">
                    ⟷ {dossier.synthesis.tensionLabel}
                  </span>
                )}
              </div>
            )}

            {/* Bottom Line */}
            <div className="rounded-xl border border-[var(--accent)]/20 bg-[var(--accent)]/5 p-5">
              <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-[var(--accent)]">
                <CheckCircle2 className="h-4 w-4" />
                {labels.bottomLine}
              </h3>
              <p className="text-sm leading-relaxed text-[var(--text)]">
                {dossier.synthesis.bottomLine}
              </p>
            </div>

            {/* Why Now (collapsible) */}
            {dossier.synthesis.whyNow && (
              <CollapsibleSection
                title="Why Now"
                icon={<Clock className="h-4 w-4 text-[var(--accent-amber)]" />}
                isCollapsed={!!collapsed['whyNow']}
                onToggle={() => toggleSection('whyNow')}
              >
                <p className="text-sm leading-relaxed text-[var(--text-muted)]">
                  {dossier.synthesis.whyNow}
                </p>
              </CollapsibleSection>
            )}

            {/* Why It Matters (collapsible) */}
            {dossier.synthesis.whyItMatters.length > 0 && (
              <CollapsibleSection
                title={labels.whyItMatters}
                icon={<TrendingUp className="h-4 w-4 text-[var(--accent-teal)]" />}
                isCollapsed={!!collapsed['whyItMatters']}
                onToggle={() => toggleSection('whyItMatters')}
              >
                <ul className="space-y-2">
                  {dossier.synthesis.whyItMatters.map((item, i) => (
                    <li
                      key={i}
                      className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm leading-relaxed text-[var(--text-muted)]"
                    >
                      {item}
                    </li>
                  ))}
                </ul>
              </CollapsibleSection>
            )}

            {/* Proof Points (collapsible) */}
            {dossier.synthesis.proofPoints.length > 0 && (
              <CollapsibleSection
                title={labels.proofPoints}
                isCollapsed={!!collapsed['proofPoints']}
                onToggle={() => toggleSection('proofPoints')}
              >
                <div className="space-y-3">
                  {dossier.synthesis.proofPoints.map((pp, i) => (
                    <div
                      key={i}
                      className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4"
                    >
                      <div className="mb-1 flex items-baseline gap-2">
                        <span className="flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full bg-[var(--accent)]/10 text-xs font-bold text-[var(--accent)]">
                          {i + 1}
                        </span>
                        <span className="text-sm font-medium text-[var(--text)]">
                          {pp.label}
                        </span>
                      </div>
                      <p className="ml-7 text-sm leading-relaxed text-[var(--text-muted)]">
                        {pp.detail}
                      </p>
                    </div>
                  ))}
                </div>
              </CollapsibleSection>
            )}

            {/* What to Watch (collapsible) */}
            {dossier.synthesis.whatToWatch.length > 0 && (
              <CollapsibleSection
                title={labels.whatToWatch}
                icon={<Eye className="h-4 w-4 text-[var(--accent-violet)]" />}
                isCollapsed={!!collapsed['whatToWatch']}
                onToggle={() => toggleSection('whatToWatch')}
              >
                <ul className="space-y-2">
                  {dossier.synthesis.whatToWatch.map((item, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-2 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm leading-relaxed text-[var(--text-muted)]"
                    >
                      <span className="mt-0.5 text-[var(--accent-violet)]">→</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </CollapsibleSection>
            )}

            {/* Suggested Questions (collapsible) */}
            {dossier.synthesis.suggestedQuestions.length > 0 && (
              <CollapsibleSection
                title={labels.questions}
                isCollapsed={!!collapsed['questions']}
                onToggle={() => toggleSection('questions')}
              >
                <div className="space-y-2">
                  {dossier.synthesis.suggestedQuestions.map((q, i) => (
                    <div
                      key={i}
                      className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm italic text-[var(--text-muted)]"
                    >
                      &ldquo;{q}&rdquo;
                    </div>
                  ))}
                </div>
              </CollapsibleSection>
            )}

            {/* Related entities — research more */}
            {relatedEntities.length > 0 && (
              <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5">
                <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-[var(--text)]">
                  <Search className="h-4 w-4 text-[var(--text-muted)]" />
                  Research next
                </h3>
                <div className="flex flex-wrap gap-2">
                  {relatedEntities.map((entity) => (
                    <button
                      key={entity.query}
                      onClick={() => onRelatedSearch(entity.query, entity.entityType)}
                      className="rounded-full border border-[var(--border-strong)] bg-[var(--bg)] px-3 py-1.5 text-sm text-[var(--text-muted)] transition-colors hover:border-[var(--accent)]/40 hover:text-[var(--accent)]"
                    >
                      {entity.query}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* RIGHT COLUMN */}
          <DossierSidebar dossier={dossier} />
        </div>
      )}
    </>
  )
}


